<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       name="ur5" >

  <xacro:property name="PI" value="3.1415926"/>
  <xacro:property name="ur5_surface_height" value="1.5"/>
  <xacro:property name="ur5_yaw" value="${PI/2}"/>

  <!-- common stuff -->
  <xacro:include filename="$(find final_project)/urdf/ur5/common.gazebo.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find final_project)/urdf/ur5/ur5.urdf.xacro" />

  <!-- gripper -->
  <xacro:include filename="$(find final_project)/urdf/ur5/ur5_gripper.urdf.xacro"/>

  <!-- arm -->
  <xacro:ur5_robot prefix="" joint_limited="true"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="${-pi}" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"
  />

  <link name="world" />

  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link = "base_link" />
    <origin xyz="0.0 0.0 ${ur5_surface_height+0.01}" rpy="0.0 0.0 ${ur5_yaw}" />
  </joint>

  <!-- add gripper -->
  <xacro:property name="initial_angle" value="${PI/6}"/>  <!-- less than PI/2 -->
  <xacro:property name="enable_initial_angle" value="false"/>

  <xacro:gripper/>

  <gazebo>
      <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
          <arm>
              <arm_name>ur5</arm_name>
              <palm_link>wrist_3_link</palm_link>
              <gripper_link>left_gripper</gripper_link>
              <gripper_link>right_gripper</gripper_link>
          </arm>
          <forces_angle_tolerance>100</forces_angle_tolerance>
          <update_rate>4</update_rate>
          <grip_count_threshold>4</grip_count_threshold>
          <max_grip_count>8</max_grip_count>
          <release_tolerance>0.005</release_tolerance>
          <disable_collisions_on_attach>false</disable_collisions_on_attach>
          <contact_topic>__default_topic__</contact_topic>
      </plugin>
  </gazebo>

</robot>
