<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ur5">

    <xacro:property name="PI" value="3.1415"/>

    <xacro:property name="initial_angle" value="${PI/6}"/>  <!-- less than PI/2 -->
    <xacro:property name="enable_initial_angle" value="false"/>

    <xacro:property name="gripper_distance" value="0.01"/>
    <xacro:property name="base_radius" value="0.005"/>
    <xacro:property name="base_length" value="0.01"/>

    <xacro:property name="scale" value="1.5"/>  <!-- default: 1.0 -->
    <xacro:property name="gripper_tip_distance" value="0.15"/> <!-- default: 0.1 -->

    <!-- half gripper -->
    <xacro:macro name="half_gripper" params="prefix reflect">

        <link name="${prefix}_gripper">
            <collision>
                <geometry>
                    <mesh filename="package://final_project/meshes/l_finger.dae" scale="${scale} 1.0 1.0"/>
                </geometry>>
                <origin rpy="${(reflect-1)/2*PI} 0 0" xyz="0 0 0"/>
            </collision>
            <visual>
                <geometry>
                    <mesh filename="package://final_project/meshes/l_finger.dae" scale="${scale} 1.0 1.0"/>
                </geometry>>
                <origin rpy="${(reflect-1)/2*PI} 0 0" xyz="0 0 0"/>
            </visual>
            <inertial>
                <origin rpy="${(reflect-1)/2*PI} 0 0" xyz="0 0 0"/>
                <mass value="0.2"/>
                <inertia ixx="1.0e-5" ixy="0.0" ixz="0.0" iyy="1.0e-5" iyz="0.0" izz="1.0e-5"/>
            </inertial>
        </link>

        <joint name="${prefix}_gripper_joint" type="revolute">
            <axis xyz="0 0 ${reflect}"/>
            <xacro:if value="${enable_initial_angle}">
                <origin rpy="${-PI/2} ${-PI/2+reflect*initial_angle} 0" xyz="${reflect*gripper_distance} 0 0"/>
            </xacro:if>
            <xacro:unless value="${enable_initial_angle}">
                <origin rpy="${-PI/2} ${-PI/2} 0" xyz="${reflect*gripper_distance} 0 0"/>
            </xacro:unless>
            <parent link="gripper_base"/>
            <child link="${prefix}_gripper"/>
            <limit effort="30" velocity="1.0" lower="0.0" upper="0.548"/>
            <dynamics damping="0.0" frictionk="0.0"/>
        </joint>

        <transmission name="${prefix}_gripper_trans">
            <type>transmisson_interface/SimpleTransmisson</type>
            <actuator name="${prefix}_gripper_moter">
                <mechanicaReduction>1</mechanicaReduction>
            </actuator>
            <joint name="${prefix}_gripper_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <link name="${prefix}_tip">
            <collision>
                <origin rpy="${(reflect-1)/2*PI} 0 0" xyz="${gripper_tip_distance} ${0.006*reflect} 0"/>
                <geometry>
                    <mesh filename="package://final_project/meshes/l_finger_tip.dae" scale="1.0 1.0 1.0"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="${(reflect-1)/2*PI} 0 0" xyz="${gripper_tip_distance} ${0.006*reflect} 0"/>
                <geometry>
                    <mesh filename="package://final_project/meshes/l_finger_tip.dae" scale="1.0 1.0 1.0"/>
                </geometry>
            </visual>
            <inertial>
                <origin rpy="${(reflect-1)/2*PI} 0 0" xyz="${gripper_tip_distance} ${0.006*reflect} 0"/>
                <mass value="0.1"/>
                <inertia ixx="1.0e-5" ixy="0.0" ixz="0.0" iyy="1.0e-5" iyz="0.0" izz="1.0e-5"/>
            </inertial>
        </link>

        <joint name="${prefix}_tip_joint" type="fixed">
            <parent link="${prefix}_gripper"/>
            <child link="${prefix}_tip"/>
        </joint>
    </xacro:macro>

    <!-- whole gripper with a base -->
    <xacro:macro name="gripper">

    <link name="gripper_base">
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>>
            <origin rpy="0 0 0" xyz="0 0 ${-base_length/2}"/>
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>>
            <origin rpy="0 0 0" xyz="0 0 ${-base_length/2}"/>
            <material name="light_grey">
                <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${-base_length/2}"/>
            <mass value="0.1"/>
            <inertia ixx="1.0e-5" ixy="0.0" ixz="0.0" iyy="1.0e-5" iyz="0.0" izz="1.0e-5"/>
        </inertial>
    </link>

    <gazebo reference="gripper_base">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <joint name="gripper_base_joint" type="fixed">
        <origin xyz="0 0 ${base_length*2}" rpy="0 0 0"/>
        <parent link="tool0"/>
        <child link="gripper_base"/>
    </joint>

    <xacro:half_gripper prefix="left" reflect="1"/>
    <xacro:half_gripper prefix="right" reflect="-1"/>

    </xacro:macro>

</robot>