# this file stores configuration options specific to the global costmap
global_costmap:
  global_frame: /map
  robot_base_frame: /EduMIP/edumip_body
  update_frequency: 2.0
  # determines whether or not the costmap should initialize itself based on
  # a map served by the map_server
  stateic_map: false
  
  rolling_windows: true

  width: 4.0
  height: 2.0
  resolution: 0.05
  origin_x: -1.0
  origin_y: -1.0
